### ISSUE TITLE
Installing MQTT Broker errors with message 

### ISSUE THREAD

**Issue by gewoondemax** [scanno/nl.scanno.mqttbroker#6]
Hello I tried to install the stable version of MQTT Broker on my Homey - the message is Homey is unreachable Try again - this is also the case for the beta version. Reason - I wanted to add the Sonoff plugin.

However - MQTT i do see in the list of services this is the last log:

0180726-09:36:42 changedSettings called
20180726-09:36:42 Restarting broker...
20180726-09:36:42 Starting broker...
20180726-09:36:42 brokerSettings: {"port":1883}
20180726-09:36:43 Mosca server is up and running
20180726-09:36:47 changedSettings called
20180726-09:36:47 Restarting broker...
20180726-09:36:47 Broker closed
20180726-09:36:47 PLAIN Config seems valid
20180726-09:36:47 Starting broker...
20180726-09:36:47 brokerSettings: {"port":1883}
20180726-09:36:47 Mosca server is up and running
20180726-09:36:51 getLogLines called
20180726-09:36:54 getLogLines called

In Homey log: Retrieving broker data failed: Error ENOENT: no such file or directory, open '/userdata/broken-users.json'

I tried first to install MQTT and after that the SONOFF and vice versa but nothing helped. Maybe some conflicts with other plug-ins? Have here: HomeKit, Fibaro Zwave, Ikea Tradfri, KlikaanKlikuit, Neo Coolcam, Sonos, Smart Presence, Buienradar, Draadloze weersensoren, WakonLan, SamsungTV
all mentioned plug-ins are mandatory.

Thank you for your help

**Comment by scanno** [comment]
The MQTT broker app is a large app to install. Very often installation exceeds the time Homey finds acceptable and as such Homey generates an error. However most of the time the broker is installed correctly.

Regarding the the error of the missing file, that one is correct because the file in question is not there yet after installation,. It will be created when you add users that can access the broker. 

Does this answer you questions?

**Comment by gewoondemax** [comment]
Yes thank you I again give it a try thank you for the quick answer!

much obliged

Max

**Comment by DIYglenn** [comment]
This issue is solved, installing larger apps does not give this error anymore.
